In [6]:
import numpy as np
import tensorflow as tf
from tensorflow.python.framework import ops

In [8]:
ops.reset_default_graph()

# Using Placeholders
sess = tf.Session()

x = tf.placeholder(tf.float32, shape=(4, 4))
y = tf.identity(x)

rand_array = np.random.rand(4, 4)

merged = tf.summary.merge_all()
writer = tf.summary.FileWriter("./variable_logs", sess.graph_def)

print(sess.run(y, feed_dict={x: rand_array}))

[[ 0.16540512  0.08080493  0.90758324  0.51629746]
 [ 0.87280297  0.45303178  0.80489659  0.56086403]
 [ 0.36319402  0.22373942  0.27583221  0.0947457 ]
 [ 0.62302768  0.22562079  0.22714001  0.10795348]]
